# Generated by Django 3.2.8 on 2022-03-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('format_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('ref', models.CharField(max_length=6)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.category')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.format')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.language')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('books_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='browse.books')),
                ('comic_id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.BooleanField()),
                ('drawer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.author')),
            ],
            bases=('browse.books',),
        ),
    ]
