# Generated by Django 3.2.8 on 2022-03-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=22, null=True)),
                ('name', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('rank', models.IntegerField(default=1)),
                ('borrow', models.ManyToManyField(to='browse.Books')),
            ],
        ),
    ]
