# Generated by Django 3.2.8 on 2022-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_auto_20220302_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='borrow',
            field=models.ManyToManyField(blank=True, null=True, to='browse.Books'),
        ),
    ]
