# Generated by Django 3.2.8 on 2022-03-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_alter_books_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='desc',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
