# Generated by Django 4.0.2 on 2022-03-06 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0007_drawer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='drawer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.drawer'),
        ),
    ]
