# Generated by Django 4.0.2 on 2022-03-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0008_alter_comic_drawer'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
