# Generated by Django 3.2.8 on 2022-03-09 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('browse', '0010_remove_users_borrow_delete_comic_delete_drawer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='borrowuser',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
